# Generated by Django 4.0.1 on 2022-02-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_contact_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='max',
        ),
    ]
