# Generated by Django 4.0.1 on 2022-04-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
    ]
